version: "3.8"

services:
  db:
    image: postgres:15
    container_name: goth
    environment:
      POSTGRES_USER: iufb
      POSTGRES_PASSWORD: leejieun
      POSTGRES_DB: goth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
